name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.19'  # Angular 17+ требует Node 20+
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Angular project
      run: npm run build -- --base-href "/Kirusha/"
      
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist/Kirusha/browser
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2