name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install and build
        run: |
          npm install
          npm run build -- --base-href "/Kirusha/"
    
      - name: Find correct build path
        run: |
          echo "=== Looking for index.html ==="
          find dist -name "index.html" -type f
          echo "=== Browser folder structure ==="
          ls -la dist/Kirusha/browser/
          echo "=== Checking for nested browser folder ==="
          ls -la dist/Kirusha/browser/browser/ 2>/dev/null || echo "No nested browser folder"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Пробуй оба варианта по очереди:
          path: dist/Kirusha/browser/browser  # ← СНАЧАЛА попробуй этот
          # path: dist/Kirusha/browser        # ← потом этот если выше не сработает
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Check assets content
        run: |
            echo "=== Assets folder files ==="
            ls -la dist/Kirusha/browser/browser/assets/
            echo "=== All PNG files in build ==="
            find dist -name "*.png" -type f